language: go
sudo: false
dist: trusty
os: centos
go:
  - 1.11

before_install:
  - go mod download
  - go get github.com/nats-io/gnatsd
  - gnatsd &

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zzgigi2003@163.com
    on_success: always
